### ISSUE TITLE
Please fix a confusing "project" reference in the text

### ISSUE THREAD

**Issue by matuskalas** [rioualen/BioHackEU23_preprint#3]
In the text "Besides, the project is highly involved in [Bioschemas]...", it doesn't make sense to me which "project" that should be talking about :( Is it the TeSS? Or the ELIXIR? Or ELIXIR Programme? Or the BH23 project 32? (TeSS and ELIXIR are however not projects)

(Btw., further in the same paragraph, the text referred to Bio.tools as a "project", what it also isn't. I fixed that in #2)

**Comment by rioualen** [comment]
It refers to TeSS, I made that clearer. Thank you!
